version: "3"
services:
  postgres:
    image: postgres:11
    ports:
      - "6432:5432"
    command: postgres
    volumes:
      - "./files/cert/server.crt:/tmp/server.crt"
      - "./files/cert/server.key:/tmp/server.key"
      - "./files/cert/ca.crt:/tmp/ca.crt"
      - "./files/pg_hba.conf:/etc/postgres/pg_hba.conf"
      - "./files/postgres.conf:/etc/postgres/postgres.conf"
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_DATABASE=postgres"
      - "POSTGRES_ROOT_PASSWORD=root"